### ISSUE TITLE
Ideiglenes streamek

### ISSUE THREAD

**Issue by dtechsrv** [vargalex/plugin.video.m4sport#1]
Szia,

Az ideiglenes streamek helyett (amiken mostanában nem láttam egyáltalán közvetítést) az M4 Sport 1-5 élő online streamjeit nem lehetne valahogy "bepakolni"?

Ezekre gondolok:
https://m4sport.hu/elo/m4sport1/
https://m4sport.hu/elo/m4sport2/
...
https://m4sport.hu/elo/m4sport5/

Most igencsak aktuális az olimpia miatt.

Köszi. ;-)

**Comment by dtechsrv** [comment]
Persze, ha a linkre kattintasz, akkor nem tölt be, de ha a címsorba hajítod a linket, akkor már egyből betölt.

A referral link nem tetszik neki:
https://dereferer.me/?https://m4sport.hu/elo/m4sport1/

Viccess ez a köz(ko)média.

**Comment by vargalex** [comment]
Szia!

Hozzáaadtam az ideiglenes stream-ok mellé. Bár, jelenleg csak az 5-ön megy valami, a többin csak jobb felül látszik a logóban az M4 SPORT 1..5..
Az új verzió elérhető a repo-ban.
Egyébként ezek a linkek az oldalon hol találhatók meg? Mondjuk én nem nézem az m4sport-ot (sem). :)

**Comment by dtechsrv** [comment]
Köszi, ez villámgyors volt. ;-)

A vicc az, hogy közvetlenül én sem találtam meg, pedig az olimpia megnyitója alatt hallottam róla a kommentátortól.
Aztán rátaláltam erre a cikkre, ebben benne voltak:
https://dereferer.me/?https://m4sport.hu/tokio2020/cikk/2021/07/23/szombati-program-es-kozvetitesek/

De máshol nem is találkoztam vele, az is lehet, hogy azóta már nagyon rejtegetik. :)

**Comment by dtechsrv** [comment]
Most például mind az 5-ön megy valami műsor, és egyik sem egyezik az M4-en futó alap műsorral.

Viszont szerintem a korábbi "ideiglenes stream"-ek azok már véglegesen döglöttek.
Nekem az a tippem, hogy ezek vannak helyettük. Csak kérdezem, hogy kellenek azok még oda vajon?
